name: ibrgy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0
  email_validator: '^2.1.16'
  day_night_switcher: ^0.2.0+1
  day_night_switch: ^1.0.4
  curved_navigation_bar: ^1.0.3
  line_awesome_flutter: ^2.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.6
  intl: ^0.17.0
  google_sign_in: ^6.2.1



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/ibrgyIcon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/icons/ibrgyIcon.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/icons/ibrgyIcon.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/icons/ibrgyIcon.png"


flutter:
  uses-material-design: true
  assets:
   - pics/alyssa.png
   - pics/apple.png
   - pics/brgy_hall.png
   - pics/brgycert.png
   - pics/brgyid.png
   - pics/brgyrecord.png
   - pics/businesscert.png
   - pics/cloudy.png
   - pics/community.png
   - pics/developerinfo.png
   - pics/facebook.png
   - pics/forgotpassword.png
   - pics/forgotpassdone.png
   - pics/google.png
   - pics/group-chat.png
   - pics/heleina.png
   - pics/ibrgy_logo.png
   - pics/ibrgy_title.png
   - pics/ibrgytitle.png
   - pics/login.png
   - pics/maria.png
   - pics/mariela.png
   - pics/marketing.png
   - pics/monitoring.png
   - pics/otherconcerns.png
   - pics/schedule.png
   - pics/signup.png
   - pics/successful.png
   - pics/thea.png
   - pics/woman.png
   - pics/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

