// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_5jbw9Kh7qKhd7PVvd190yUX43wrgpg',
    appId: '1:686174062201:web:990d3c20d63117e472b6a8',
    messagingSenderId: '686174062201',
    projectId: 'ibrgy-app-ccb3a',
    authDomain: 'ibrgy-app-ccb3a.firebaseapp.com',
    storageBucket: 'ibrgy-app-ccb3a.appspot.com',
    measurementId: 'G-MCC51YTG6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKHJe5lO8nct8RRy52JGKSVfzI0jFuDws',
    appId: '1:686174062201:android:4a0b71a43c9e1e8b72b6a8',
    messagingSenderId: '686174062201',
    projectId: 'ibrgy-app-ccb3a',
    storageBucket: 'ibrgy-app-ccb3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEP1EPsS0ziX1XlQELCmcF4EAt5ixAAz8',
    appId: '1:686174062201:ios:b3e018bcc659487a72b6a8',
    messagingSenderId: '686174062201',
    projectId: 'ibrgy-app-ccb3a',
    storageBucket: 'ibrgy-app-ccb3a.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
